<?php

declare(strict_types=1);

namespace App\Permissions;

use App\Enums\Role;
use Laravel\Jetstream\Jetstream;

/**
 * Core permissions for existing Solidtime features.
 * Extracted from JetstreamServiceProvider to follow the modular pattern (SF-08).
 */
class CorePermissions
{
    public static function register(): void
    {
        Jetstream::role(Role::Owner->value, 'Owner', [
            'charts:view:own',
            'charts:view:all',
            'projects:view',
            'projects:view:all',
            'projects:create',
            'projects:update',
            'projects:delete',
            'project-members:view',
            'project-members:create',
            'project-members:update',
            'project-members:delete',
            'tasks:view',
            'tasks:view:all',
            'tasks:create',
            'tasks:create:all',
            'tasks:update',
            'tasks:update:all',
            'tasks:delete',
            'tasks:delete:all',
            'time-entries:view:all',
            'time-entries:create:all',
            'time-entries:update:all',
            'time-entries:delete:all',
            'time-entries:view:own',
            'time-entries:create:own',
            'time-entries:update:own',
            'time-entries:delete:own',
            'tags:view',
            'tags:create',
            'tags:update',
            'tags:delete',
            'clients:view',
            'clients:view:all',
            'clients:create',
            'clients:update',
            'clients:delete',
            'organizations:view',
            'organizations:update',
            'organizations:delete',
            'import',
            'export',
            'invitations:view',
            'invitations:create',
            'invitations:resend',
            'invitations:remove',
            'members:view',
            'members:invite-placeholder',
            'members:change-ownership',
            'members:make-placeholder',
            'members:merge-into',
            'members:update',
            'members:delete',
            'billing',
            'reports:view',
            'reports:create',
            'reports:update',
            'reports:delete',
            'invoices:view',
            'invoices:create',
            'invoices:update',
            'invoices:download',
            'invoices:delete',
            'invoice-settings:view',
            'invoice-settings:update',
            'notifications:view',
            'notifications:manage',
        ])->description('Owner users can perform any action. There is only one owner per organization.');

        Jetstream::role(Role::Admin->value, 'Administrator', [
            'charts:view:own',
            'charts:view:all',
            'projects:view',
            'projects:view:all',
            'projects:create',
            'projects:update',
            'projects:delete',
            'project-members:view',
            'project-members:create',
            'project-members:update',
            'project-members:delete',
            'tasks:view',
            'tasks:view:all',
            'tasks:create',
            'tasks:create:all',
            'tasks:update',
            'tasks:update:all',
            'tasks:delete',
            'tasks:delete:all',
            'time-entries:view:all',
            'time-entries:create:all',
            'time-entries:update:all',
            'time-entries:delete:all',
            'time-entries:view:own',
            'time-entries:create:own',
            'time-entries:update:own',
            'time-entries:delete:own',
            'tags:view',
            'tags:create',
            'tags:update',
            'tags:delete',
            'clients:view',
            'clients:view:all',
            'clients:create',
            'clients:update',
            'clients:delete',
            'organizations:view',
            'organizations:update',
            'import',
            'export',
            'invitations:view',
            'invitations:create',
            'invitations:resend',
            'invitations:remove',
            'members:view',
            'members:invite-placeholder',
            'members:make-placeholder',
            'members:merge-into',
            'members:delete',
            'members:update',
            'reports:view',
            'reports:create',
            'reports:update',
            'reports:delete',
            'invoices:view',
            'invoices:create',
            'invoices:update',
            'invoices:download',
            'invoices:delete',
            'invoice-settings:view',
            'invoice-settings:update',
            'notifications:view',
            'notifications:manage',
        ])->description('Administrator users can perform any action, except accessing the billing dashboard.');

        Jetstream::role(Role::Manager->value, 'Manager', [
            'charts:view:own',
            'charts:view:all',
            'projects:view',
            'projects:view:all',
            'projects:create',
            'projects:update',
            'projects:delete',
            'project-members:view',
            'project-members:create',
            'project-members:update',
            'project-members:delete',
            'tasks:view',
            'tasks:view:all',
            'tasks:create',
            'tasks:create:all',
            'tasks:update',
            'tasks:update:all',
            'tasks:delete',
            'tasks:delete:all',
            'time-entries:view:all',
            'time-entries:create:all',
            'time-entries:update:all',
            'time-entries:delete:all',
            'time-entries:view:own',
            'time-entries:create:own',
            'time-entries:update:own',
            'time-entries:delete:own',
            'tags:view',
            'tags:create',
            'tags:update',
            'tags:delete',
            'clients:view',
            'clients:view:all',
            'clients:create',
            'clients:update',
            'clients:delete',
            'organizations:view',
            'invitations:view',
            'members:view',
            'reports:view',
            'reports:create',
            'reports:update',
            'reports:delete',
            'invoices:view',
            'invoices:create',
            'invoices:update',
            'invoices:download',
            'invoices:delete',
            'invoice-settings:view',
            'invoice-settings:update',
            'notifications:view',
        ])->description('Managers have full access to all projects, time entries, etc. but cannot manage the organization.');

        Jetstream::role(Role::Employee->value, 'Employee', [
            'charts:view:own',
            'projects:view',
            'tags:view',
            'tasks:view',
            'clients:view',
            'time-entries:view:own',
            'time-entries:create:own',
            'time-entries:update:own',
            'time-entries:delete:own',
            'organizations:view',
            'notifications:view',
        ])->description('Employees have the ability to read, create, and update their own time entries.');

        Jetstream::role(Role::Placeholder->value, 'Placeholder', [
        ])->description('Placeholders are used for importing data. They cannot log in and have no permissions.');
    }
}
